apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins-k8s-demo
  namespace: production

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jenkins-k8s-demo

  template:
    metadata:
      labels:
        app: jenkins-k8s-demo

    spec:
      imagePullSecrets:
        - name: harbor-registry

      containers:
        - name: nginx
          image: 192.168.56.101:8088/k8s-lab/jenkins-k8s-demo:ci-placeholder
          imagePullPolicy: Always

          ports:
            - containerPort: 80

